### ISSUE TITLE
Error during vagrant up

### ISSUE THREAD

**Issue by pradeepn-altran** [lukeelten/openshift-vagrant#1]
I am getting the following error after doing a vagrant up. Appreciate any pointers. 
Possible I am missing some package/software.  I did run the install_plugin.sh to install all vagrant plugins prior to the run.

'''
Dependency Updated:
  glibc.x86_64 0:2.17-260.el7_6.6     glibc-common.x86_64 0:2.17-260.el7_6.6

Complete!
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 6.0.6 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.0.6 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
3.10.0-957.12.2.el7.x86_64.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> master1: Checking for guest additions in VM...
==> master1: Setting hostname...
==> master1: Configuring and enabling network interfaces...
==> master1: Automatic installation for Landrush IP not enabled
==> master1: [landrush] Using eth1 (192.168.50.20)
==> master1: [landrush] DNS server already running with pid 24340
==> master1: [landrush] Using eth1 (192.168.50.20)
==> master1: Running cleanup tasks for 'reload' provisioner...
==> master1: Forcing shutdown of VM...
==> master1: Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:289:in `OpenKey': The system cannot find the file specified. (Win32::Registry::Error)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:431:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/Users/Administrator/.vagrant.d/gems/2.4.4/gems/landrush-1.3.2/lib/landrush/cap/host/windows/configure_visibility_on_host.rb:160:in `update_network_adapter'
        from C:/Users/Administrator/.vagrant.d/gems/2.4.4/gems/landrush-1.3.2/lib/landrush/cap/host/windows/configure_visibility_on_host.rb:18:in `configure_visibility_on_host'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:111:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:111:in `capability'
        from C:/Users/Administrator/.vagrant.d/gems/2.4.4/gems/landrush-1.3.2/lib/landrush/action/setup.rb:43:in `post_boot_setup'
        from C:/Users/Administrator/.vagrant.d/gems/2.4.4/gems/landrush-1.3.2/lib/landrush/action/setup.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
'''

**Comment by pradeepn-altran** [comment]
Just curious, I also see there is a similar project here with the same name 
https://github.com/eliu/openshift-vagrant
